version: '3.4'

services:
  phpfpm:
    container_name: '${APP_NAME}'
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    environment:
      - XDEBUG_CONFIG=remote_host=172.0.0.1 remote_enable=on
      - APP_XDEBUG=enabled
      - COMPOSER_AUTH=$COMPOSER_AUTH
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    depends_on:
      - mariadb
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "5"

  nginx:
    image: nginx:latest
    networks:
      - app_network
    ports:
      - '127.0.0.1:${APP_PORT}:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html/
    restart: always

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb_volume:/var/lib/mysql'
    networks:
      - app_network
    ports:
      - '127.0.0.1:${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  mailhog:
    restart: always
    image: mailhog/mailhog
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
  redis_volume:
    driver: local
